#!/usr/bin/env bash
# script to send file to spacific path by scp

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

filePath=$1
IP=$2
userName=$3
pathSSH=$4

scp -o StrictHostKeyChecking=no -i "$pathSSH" "$filePath" "$userName@$IP:~/"

exit 0