#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.
sudo su
apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
chown -R www-data:www-data /etc/nginx/html
chmod -R 755 /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen	80;
    listen	[::]:80 default_server;
    root	/etc/nginx/html;
    index	index.html index.htm;
}
" > /etc/nginx/sites-available/default
service nginx restart